def open_pr(username, tree_data, candidate_result=None):
    branch_name = f"update-tree-{username}"
    if candidate_result:
        title = f"[user] Update {username} skill tree - added {candidate_result}"
    else:
        title = f"[user] Update {username} skill tree"
    body = f"Detected new skills and confirmed fusions for {username}.\n\nAutomatically generated by Gaia plugin."
    print(f"Mock: Opening PR to gaia-registry/gaia")
    print(f"Branch: {branch_name}")
    print(f"Title: {title}")
    print(f"Body: {body}")
    print("Success: PR #42 opened.")
    return "https://github.com/gaia-registry/gaia/pull/42"


def open_intake_pr(username, batch_data, batch_path=None):
    branch_name = f"push-skills-{username}-{batch_data.get('batchId')}"
    title = f"[intake] {username} skill batch - {batch_data.get('sourceRepo')}"
    body = (
        f"Submitted {len(batch_data.get('knownSkills', []))} known skills and "
        f"{len(batch_data.get('proposedSkills', []))} proposed skills from "
        f"{batch_data.get('sourceRepo')}.\n\n"
        "Automatically generated by `gaia push`."
    )
    print("Mock: Opening PR to gaia-registry/gaia")
    print(f"Branch: {branch_name}")
    print(f"Title: {title}")
    print(f"Body: {body}")
    if batch_path:
        print(f"Batch: {batch_path}")
    print("Success: PR #42 opened.")
    return "https://github.com/gaia-registry/gaia/pull/42"
