#!/usr/bin/env python3
"""Generate docs/api/v1/ — static JSON projection of the Gaia Public Trust API.

Usage:
    python scripts/buildApiProjection.py --out-dir <path>

Reads:
    registry/named-skills.json   (Class P — gitignored, generated by gaia dev docs)
    docs/graph/ledger/data.json  (Class S — tracked)
    registry/schema/meta.json    (tracked)
    pyproject.toml               (tracked)

Writes:
    <out-dir>/
        health.json
        skills/index.json
        skills/page-{N}.json
        skills/<contributor>/<skill>.json
        contributors/index.json
        contributors/<handle>.json
        leaderboard.json
        evidence-types.json
        search-index.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from gaia_cli.redaction import is_redacted  # noqa: E402

PAGE_SIZE = 50

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_version() -> str:
    """Extract version string from pyproject.toml via regex (no tomllib dep)."""
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    m = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    return m.group(1) if m else "0.0.0"


def _write_json(path: Path, obj: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2), encoding="utf-8")


def _slug_from_id(skill_id: str) -> tuple[str, str]:
    """Split 'contributor/skill-name' into (contributor, skill_slug)."""
    parts = skill_id.split("/", 1)
    if len(parts) == 2:
        return parts[0], parts[1]
    return skill_id, skill_id


def _slim_projection(entry: dict) -> dict:
    """Return the slim fields used in list/pagination responses."""
    contributor, slug = _slug_from_id(entry.get("id", ""))
    return {
        "id": entry.get("id", ""),
        "name": entry.get("name", ""),
        "level": entry.get("level", ""),
        "trustMagnitude": entry.get("trustMagnitude", 0),
        "overallTrustGrade": entry.get("overallTrustGrade"),
        "contributor": entry.get("contributor", contributor),
        "type": entry.get("type", "basic"),
        "_links": {
            "self": f"/api/v1/skills/{contributor}/{slug}.json",
        },
    }


def _full_projection(entry: dict) -> dict:
    """Return the full record including evidence, timeline, suiteComponents, etc."""
    contributor, slug = _slug_from_id(entry.get("id", ""))
    contrib = entry.get("contributor", contributor)

    # suiteComponents must be list of ID strings, NOT inline objects
    suite_raw = entry.get("suiteComponents")
    if suite_raw and isinstance(suite_raw, list):
        suite = []
        for item in suite_raw:
            if isinstance(item, str):
                suite.append(item)
            elif isinstance(item, dict):
                # Flatten: use 'id' key if present, else str representation
                suite.append(item.get("id", str(item)))
        suite_components = suite
    elif suite_raw is None:
        suite_components = None
    else:
        suite_components = suite_raw

    result: dict = {
        "id": entry.get("id", ""),
        "name": entry.get("name", ""),
        "contributor": contrib,
        "level": entry.get("level", ""),
        "type": entry.get("type", "basic"),
        "status": entry.get("status", "named"),
        "trustMagnitude": entry.get("trustMagnitude", 0),
        "overallTrustGrade": entry.get("overallTrustGrade"),
        "_links": {
            "self": f"/api/v1/skills/{contributor}/{slug}.json",
            "contributor": f"/api/v1/contributors/{contrib}.json",
            "list": "/api/v1/skills/index.json",
        },
    }

    # Optional fields — include only when present
    for key in ("title", "genericSkillRef", "origin", "description", "tags",
                "apexGateStatus", "evidence", "timeline", "links"):
        if key in entry:
            result[key] = entry[key]

    if suite_components is not None:
        result["suiteComponents"] = suite_components

    return result


def _tokens_for_skill(entry: dict) -> list[str]:
    """Build a list of lowercase search tokens for this skill."""
    token_set: set[str] = set()

    name = entry.get("name", "")
    for word in re.split(r"[\s\-_/]+", name.lower()):
        if word:
            token_set.add(word)

    desc = entry.get("description", "")
    for word in re.split(r"[\s\-_/.,;:!?]+", (desc or "")[:200].lower()):
        if word:
            token_set.add(word)

    ref = entry.get("genericSkillRef", "")
    if ref:
        for word in re.split(r"[\-_/]+", ref.lower()):
            if word:
                token_set.add(word)

    for tag in entry.get("tags", []) or []:
        for word in re.split(r"[\s\-_/]+", str(tag).lower()):
            if word:
                token_set.add(word)

    # Filter out trivial tokens
    stopwords = {"a", "an", "the", "of", "in", "on", "at", "to", "for",
                 "and", "or", "with", "by", "from", "as", "is", "it"}
    return sorted(token_set - stopwords)


# ---------------------------------------------------------------------------
# Endpoint builders
# ---------------------------------------------------------------------------


def build_health(out_dir: Path, version: str, generated_at: str, skill_count: int) -> None:
    """Write health.json."""
    _write_json(out_dir / "health.json", {
        "ok": True,
        "version": version,
        "registryGeneratedAt": generated_at,
        "namedSkillsCount": skill_count,
    })


def build_skills_pages(out_dir: Path, skills: list[dict]) -> None:
    """Write skills/index.json and skills/page-{N}.json for paginated list."""
    total = len(skills)
    total_pages = max(1, -(-total // PAGE_SIZE))  # ceiling division

    skills_dir = out_dir / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    slim = [_slim_projection(e) for e in skills]

    for i in range(total_pages):
        page_num = i + 1
        page_skills = slim[i * PAGE_SIZE: (i + 1) * PAGE_SIZE]

        self_path = "index.json" if page_num == 1 else f"page-{page_num}.json"
        links: dict = {"self": f"/api/v1/skills/{self_path}"}
        if page_num > 1:
            prev_path = "index.json" if page_num == 2 else f"page-{page_num - 1}.json"
            links["prev"] = f"/api/v1/skills/{prev_path}"
        if page_num < total_pages:
            links["next"] = f"/api/v1/skills/page-{page_num + 1}.json"

        payload = {
            "skills": page_skills,
            "page": page_num,
            "totalPages": total_pages,
            "totalSkills": total,
            "_links": links,
        }
        _write_json(skills_dir / self_path, payload)


def build_skill_detail_files(out_dir: Path, skills: list[dict]) -> None:
    """Write one JSON file per named skill under skills/<contributor>/<skill>.json."""
    for entry in skills:
        contributor, slug = _slug_from_id(entry.get("id", ""))
        path = out_dir / "skills" / contributor / f"{slug}.json"
        _write_json(path, _full_projection(entry))


def build_contributors(out_dir: Path, skills: list[dict]) -> None:
    """Write contributors/index.json and contributors/<handle>.json."""
    # Group by contributor
    by_contrib: dict[str, list[dict]] = {}
    for entry in skills:
        contributor, _ = _slug_from_id(entry.get("id", ""))
        handle = entry.get("contributor", contributor)
        by_contrib.setdefault(handle, []).append(entry)

    # Remove contributors with zero non-redacted skills
    visible = {h: s for h, s in by_contrib.items() if s}

    contributor_summaries = []
    for handle, contrib_skills in visible.items():
        prestige = round(sum(s.get("trustMagnitude", 0) for s in contrib_skills), 2)
        top_skill = max(contrib_skills, key=lambda s: s.get("trustMagnitude", 0))
        contributor, slug = _slug_from_id(top_skill.get("id", ""))

        summary = {
            "handle": handle,
            "namedSkills": len(contrib_skills),
            "topSkill": {
                "id": top_skill.get("id", ""),
                "level": top_skill.get("level", ""),
                "trustMagnitude": top_skill.get("trustMagnitude", 0),
            },
            "prestigeScore": prestige,
            "_links": {
                "self": f"/api/v1/contributors/{handle}.json",
            },
        }
        contributor_summaries.append(summary)

    # Sort by prestige descending
    contributor_summaries.sort(key=lambda c: c["prestigeScore"], reverse=True)

    contribs_dir = out_dir / "contributors"
    contribs_dir.mkdir(parents=True, exist_ok=True)

    _write_json(contribs_dir / "index.json", {
        "contributors": contributor_summaries,
        "totalContributors": len(contributor_summaries),
        "_links": {"self": "/api/v1/contributors/index.json"},
    })

    # Per-contributor detail files
    for handle, contrib_skills in visible.items():
        prestige = round(sum(s.get("trustMagnitude", 0) for s in contrib_skills), 2)
        top_skill = max(contrib_skills, key=lambda s: s.get("trustMagnitude", 0))

        # Grade distribution
        grade_dist: dict[str, int] = {}
        for s in contrib_skills:
            grade = s.get("overallTrustGrade")
            key = grade if grade else "ungraded"
            grade_dist[key] = grade_dist.get(key, 0) + 1

        detail = {
            "handle": handle,
            "namedSkills": [_slim_projection(s) for s in contrib_skills],
            "namedSkillsCount": len(contrib_skills),
            "topSkill": {
                "id": top_skill.get("id", ""),
                "level": top_skill.get("level", ""),
                "trustMagnitude": top_skill.get("trustMagnitude", 0),
            },
            "prestigeScore": prestige,
            "gradeDistribution": grade_dist,
            "_links": {
                "self": f"/api/v1/contributors/{handle}.json",
                "list": "/api/v1/contributors/index.json",
            },
        }
        _write_json(contribs_dir / f"{handle}.json", detail)


def build_leaderboard(out_dir: Path, ledger_path: Path) -> None:
    """Write leaderboard.json by reshaping docs/graph/ledger/data.json."""
    if not ledger_path.exists():
        _write_json(out_dir / "leaderboard.json", {
            "distribution": {},
            "rows": [],
            "_links": {"self": "/api/v1/leaderboard.json"},
        })
        return

    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))

    # Strip internal top-level fields
    _STRIP_TOP = {"version", "generatedAt"}
    distribution = ledger.get("summary", {})

    # Reshape rows
    _STRIP_ROW = {"mayStars", "juneStars", "g7Stars", "flag", "apexResults"}
    rows = []
    for row in ledger.get("rows", []):
        reshaped = {}
        for k, v in row.items():
            if k in _STRIP_ROW:
                continue
            if k == "skillId":
                reshaped["id"] = v
            elif k == "tm":
                reshaped["trustMagnitude"] = v
            elif k == "currentStars":
                reshaped["level"] = v
            else:
                reshaped[k] = v
        rows.append(reshaped)

    _write_json(out_dir / "leaderboard.json", {
        "distribution": distribution,
        "rows": rows,
        "_links": {"self": "/api/v1/leaderboard.json"},
    })


def build_evidence_types(out_dir: Path, schema_path: Path) -> None:
    """Write evidence-types.json from registry/schema/meta.json."""
    if not schema_path.exists():
        _write_json(out_dir / "evidence-types.json", {
            "types": [],
            "gradeThresholds": {},
            "_links": {"self": "/api/v1/evidence-types.json"},
        })
        return

    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    evidence = schema.get("evidence", {})
    _write_json(out_dir / "evidence-types.json", {
        "types": evidence.get("types", []),
        "gradeThresholds": evidence.get("gradeThresholds", {}),
        "_links": {"self": "/api/v1/evidence-types.json"},
    })


def build_search_index(out_dir: Path, skills: list[dict]) -> None:
    """Write search-index.json — flat token array for client-side search."""
    entries = []
    for entry in skills:
        entries.append({
            "id": entry.get("id", ""),
            "name": entry.get("name", ""),
            "contributor": entry.get("contributor", ""),
            "level": entry.get("level", ""),
            "grade": entry.get("overallTrustGrade"),
            "trustMagnitude": entry.get("trustMagnitude", 0),
            "tokens": _tokens_for_skill(entry),
        })
    _write_json(out_dir / "search-index.json", entries)


# ---------------------------------------------------------------------------
# Main entrypoint
# ---------------------------------------------------------------------------


def run(out_dir: Path) -> int:
    """Execute the full projection. Returns 0 on success, 1 on fatal error."""
    named_path = ROOT / "registry" / "named-skills.json"

    if not named_path.exists():
        print(
            f"FATAL: {named_path} not found. Run `gaia dev docs` first.",
            file=sys.stderr,
        )
        return 1

    try:
        data = json.loads(named_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"FATAL: {named_path} is malformed: {e}", file=sys.stderr)
        return 1

    if "buckets" not in data:
        print(f"FATAL: {named_path} missing 'buckets' key.", file=sys.stderr)
        return 1

    # Flatten all buckets — NEVER read awaitingClassification
    all_skills: list[dict] = []
    for bucket in data["buckets"].values():
        if isinstance(bucket, list):
            all_skills.extend(bucket)

    # Apply redaction: exclude 1★/Awakened skills
    visible_skills = [e for e in all_skills if not is_redacted(e.get("level", ""))]

    # Sort: TM descending, then id ascending as stable tiebreak
    visible_skills.sort(
        key=lambda e: (-e.get("trustMagnitude", 0), e.get("id", ""))
    )

    version = _read_version()
    generated_at = data.get("generatedAt", "")

    out_dir.mkdir(parents=True, exist_ok=True)

    # Build all endpoints
    build_health(out_dir, version, generated_at, len(visible_skills))
    build_skills_pages(out_dir, visible_skills)
    build_skill_detail_files(out_dir, visible_skills)
    build_contributors(out_dir, visible_skills)
    build_leaderboard(
        out_dir, ROOT / "docs" / "graph" / "ledger" / "data.json"
    )
    build_evidence_types(out_dir, ROOT / "registry" / "schema" / "meta.json")
    build_search_index(out_dir, visible_skills)

    return 0


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        description="Generate docs/api/v1/ static JSON projection."
    )
    parser.add_argument(
        "--out-dir",
        required=True,
        help="Output directory (will be created if it doesn't exist)",
    )
    args = parser.parse_args(argv)
    rc = run(Path(args.out_dir))
    sys.exit(rc)


if __name__ == "__main__":
    main()
