"""
scripts.upstream_watcher.issuer — GitHub issue creation for the watcher.

Responsible for:
- Rendering issue bodies (umbrella, bootstrap, child intake).
- Idempotency checks (skip if matching open issue already exists).
- ``gh issue create`` invocations.
- Post-creation umbrella body edit to add child-intake cross-references.

Public API
----------
render_umbrella_body(finding, mode)
    Return the full markdown body for an umbrella ``[upstream:release]`` issue.

render_bootstrap_body(finding)
    Return the full markdown body for a ``[upstream:bootstrap]`` issue.

render_child_body(slug, contributor, umbrella_number, suite_gh_url)
    Return the markdown body for a child ``[intake]`` issue.

create_issues(findings, apply, verbose)
    Main entry point: for each finding, check idempotency, create issues
    (if --apply), and return a summary dict.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Label vocab table (embedded in issue bodies, per design §5)
# ---------------------------------------------------------------------------

_LABEL_VOCAB = """
| Label | Meaning |
|---|---|
| `upstream:approved` | Approve — watcher will open a draft sync PR |
| `upstream:rejected` | Reject — skip this release; child intakes auto-closed |
| `upstream:needs-info` | Hold — waiting for more information |
| `skip-child-gate` | Bypass child-intake resolution check (use with `upstream:approved`) |
""".strip()

_REVIEWER_ACTIONS = """
| Action | How |
|---|---|
| Approve sync | Apply `upstream:approved` label |
| Reject | Apply `upstream:rejected` label |
| Hold | Apply `upstream:needs-info` label |
| Force-approve (skip child gate) | Apply `skip-child-gate` + `upstream:approved` |
""".strip()


# ---------------------------------------------------------------------------
# Body renderers
# ---------------------------------------------------------------------------


def _payload_block(payload: dict) -> str:
    """Wrap a dict as a machine-readable payload block in the issue body."""
    json_str = json.dumps(payload, indent=2)
    return (
        "<!-- gaia-upstream-payload\n"
        f"{json_str}\n"
        "-->"
    )


def render_umbrella_body(
    finding: dict,
    mode: str,
    component_adds: list[str],
    component_removes: list[str],
    link_liveness: list[dict],
) -> str:
    """Render the full body for an umbrella ``[upstream:release]`` issue."""
    skill_id = finding["skillId"]
    prev_version = finding.get("currentVersion", "none")
    new_version = finding["newVersion"]
    released_at = finding.get("releasedAt", "")
    source_url = finding.get("sourceUrl", "")

    # Machine-readable payload
    payload = {
        "skillId": skill_id,
        "previousVersion": prev_version,
        "newVersion": new_version,
        "releasedAt": released_at,
        "sourceUrl": source_url,
        "mode": mode,
        "componentAdds": component_adds,
        "componentRemoves": component_removes,
        "linkLiveness": link_liveness,
    }

    # Human-readable sections
    adds_section = ""
    if component_adds:
        lines = [f"- `+ {slug}` (child intake: _pending_)" for slug in component_adds]
        adds_section = "\n".join(lines)
    else:
        adds_section = "_No new components detected._"

    removes_section = ""
    if component_removes:
        lines = [f"- `- {slug}` (will be **frozen** on approval)" for slug in component_removes]
        removes_section = "\n".join(lines)
    else:
        removes_section = "_No removed components detected._"

    liveness_section = ""
    if link_liveness:
        rows = [f"| `{r['skillId']}` | `{r['url']}` | `{r['status']}` |"
                for r in link_liveness]
        liveness_section = (
            "| Skill | URL | Status |\n"
            "|---|---|---|\n"
            + "\n".join(rows)
        )
    else:
        liveness_section = "_All component links are healthy._"

    mode_note = (
        "**Mode:** `components` — component diff and link-liveness checks were performed."
        if mode == "components"
        else "**Mode:** `version-only` — component layout not detected in upstream repo; only version bump tracked."
    )

    return f"""## Upstream release detected

> Auto-generated by the Gaia upstream watcher. See [upstream-watcher.md](https://github.com/gaia-research/gaia-skill-tree/blob/main/docs/agents/upstream-watcher.md) for the full design spec.

{_payload_block(payload)}

---

### Version

**`{skill_id}`** was at `{prev_version}` → upstream is now **`{new_version}`**
Released: `{released_at}`
Source: {source_url}

{mode_note}

---

### Component changes

**Added upstream:**

{adds_section}

**Removed upstream:**

{removes_section}

---

### Link liveness

{liveness_section}

---

### Label vocab

{_LABEL_VOCAB}

---

### Reviewer actions

{_REVIEWER_ACTIONS}
"""


def render_bootstrap_body(finding: dict) -> str:
    """Render body for a ``[upstream:bootstrap]`` issue."""
    skill_id = finding["skillId"]
    new_version = finding["newVersion"]
    released_at = finding.get("releasedAt", "")
    source_url = finding.get("sourceUrl", "")

    payload = {
        "skillId": skill_id,
        "previousVersion": None,
        "newVersion": new_version,
        "releasedAt": released_at,
        "sourceUrl": source_url,
        "mode": "bootstrap",
        "componentAdds": [],
        "componentRemoves": [],
        "linkLiveness": [],
    }

    return f"""## Upstream watcher — first-time baseline

> The Gaia upstream watcher has encountered **`{skill_id}`** for the first time.
> No `upstream:` block exists in its frontmatter yet.
>
> Approving this issue will write the initial `upstream:` block, baselining
> at the current upstream release `{new_version}`. No component diff or
> description changes are proposed — this is purely a one-time confirmation
> that the watcher has derived the correct `owner/repo` from `links.github`.

{_payload_block(payload)}

---

### Proposed baseline

- **Skill:** `{skill_id}`
- **Baseline version:** `{new_version}`
- **Released:** `{released_at}`
- **Source:** {source_url}

---

### Label vocab

{_LABEL_VOCAB}

---

### Reviewer actions

{_REVIEWER_ACTIONS}
"""


def render_child_body(
    slug: str,
    contributor: str,
    umbrella_number: int | str,
    suite_gh_url: str,
) -> str:
    """Render body for a child ``[intake]`` issue."""
    # Derive a best-guess skill ID and GitHub link
    # component paths like "skills/foo-bar" → contributor/foo-bar
    owner_repo = None
    from scripts.lib.github_api import parse_owner_repo
    parsed = parse_owner_repo(suite_gh_url)
    if parsed:
        owner_repo = f"{parsed[0]}/{parsed[1]}"

    suggested_id = f"{contributor}/{slug}"
    skill_md_url = ""
    if owner_repo:
        skill_md_url = f"https://github.com/{owner_repo}/blob/main/skills/{slug}/SKILL.md"

    return f"""> Auto-populated by upstream watcher. Umbrella: #{umbrella_number}.

---

## New skill intake proposal

**Suggested ID:** `{suggested_id}`
**Name:** _{slug}_ (update with canonical title from SKILL.md)
**Contributor:** `{contributor}`

### Attribution

- **type:** `attributed`
- **upstream_author:** `{contributor}`

### Evidence

- **type:** `repo`
- **url:** {skill_md_url if skill_md_url else '_unknown — check upstream repo_'}

---

### Description

_Auto-detected from upstream release. Review SKILL.md for the canonical description._

---

### Checklist

- [ ] Confirm skill ID matches upstream directory name
- [ ] Copy description from upstream SKILL.md
- [ ] Verify `links.github` blob URL resolves
- [ ] Assign `genericSkillRef` from the registry
- [ ] Set star level per META.md §2

---

> This issue was auto-created by the Gaia upstream watcher.
> Umbrella: #{umbrella_number}
"""


# ---------------------------------------------------------------------------
# Idempotency check
# ---------------------------------------------------------------------------


def _find_existing_issue(search_str: str, label: str) -> int | None:
    """Return the number of an open issue matching *search_str* and *label*, or None."""
    try:
        result = subprocess.run(
            [
                "gh", "issue", "list",
                "--label", label,
                "--state", "open",
                "--search", search_str,
                "--json", "number,title",
            ],
            capture_output=True,
            text=True,
            timeout=30,
        )
        if result.returncode != 0:
            return None
        issues = json.loads(result.stdout or "[]")
        for issue in issues:
            if search_str in issue.get("title", ""):
                return issue["number"]
    except Exception as exc:  # noqa: BLE001
        print(f"  [warn] idempotency check failed: {exc}", file=sys.stderr)
    return None


# ---------------------------------------------------------------------------
# Issue creation
# ---------------------------------------------------------------------------


def _create_issue(
    title: str,
    labels: list[str],
    body: str,
    dry_run: bool,
    verbose: bool = False,
) -> int | None:
    """Create a GitHub issue.  Returns the new issue number or None."""
    if dry_run:
        if verbose:
            print(f"  [dry-run] Would create issue: {title!r}", file=sys.stderr)
        return None

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".md", delete=False, encoding="utf-8"
    ) as f:
        f.write(body)
        body_file = f.name

    try:
        cmd = [
            "gh", "issue", "create",
            "--title", title,
            "--label", ",".join(labels),
            "--body-file", body_file,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            print(
                f"  [error] gh issue create failed: {result.stderr}",
                file=sys.stderr,
            )
            return None
        # Output is the issue URL; extract number
        url = result.stdout.strip()
        m = re.search(r"/issues/(\d+)", url)
        if m:
            num = int(m.group(1))
            print(f"  Created issue #{num}: {title}", file=sys.stderr)
            return num
        return None
    finally:
        Path(body_file).unlink(missing_ok=True)


def _edit_umbrella_body(
    umbrella_number: int,
    child_numbers: list[int],
    dry_run: bool,
) -> None:
    """Append child-intake cross-references to the umbrella issue body."""
    if dry_run or not child_numbers:
        return
    refs = ", ".join(f"#{n}" for n in child_numbers)
    comment_body = f"Child intakes: {refs}"
    try:
        subprocess.run(
            [
                "gh", "issue", "comment",
                str(umbrella_number),
                "--body", comment_body,
            ],
            check=True,
            capture_output=True,
            timeout=30,
        )
    except Exception as exc:  # noqa: BLE001
        print(
            f"  [warn] Could not comment child refs on #{umbrella_number}: {exc}",
            file=sys.stderr,
        )


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------


def create_issues(
    full_findings: list[dict],
    apply: bool,
    verbose: bool = False,
) -> list[dict]:
    """Process all findings and create issues.

    Parameters
    ----------
    full_findings:
        Each dict has keys: finding_type, skillId, mode, currentVersion,
        newVersion, releasedAt, sourceUrl, componentAdds, componentRemoves,
        linkLiveness.
    apply:
        If False, dry-run mode — print but don't create.
    verbose:
        Extra logging.

    Returns
    -------
    list[dict]
        Summary records per finding.
    """
    summaries: list[dict] = []

    for finding in full_findings:
        skill_id = finding["skillId"]
        finding_type = finding["finding_type"]
        new_version = finding["newVersion"]
        contributor = skill_id.split("/")[0] if "/" in skill_id else skill_id

        # ── Bootstrap ──────────────────────────────────────────────────────
        if finding_type == "bootstrap":
            title = f"[upstream:bootstrap] {skill_id} → baseline at {new_version}"
            existing = _find_existing_issue(
                f"{skill_id} → baseline at {new_version}", "upstream:bootstrap"
            )
            if existing:
                print(
                    f"  Bootstrap for {skill_id}@{new_version} already exists as #{existing}; skipping.",
                    file=sys.stderr,
                )
                summaries.append(
                    {"type": "bootstrap", "skillId": skill_id, "skipped": True, "issue": existing}
                )
                continue

            body = render_bootstrap_body(finding)
            issue_num = _create_issue(
                title,
                ["upstream:bootstrap", "needs-triage"],
                body,
                dry_run=not apply,
                verbose=verbose,
            )
            summaries.append(
                {"type": "bootstrap", "skillId": skill_id, "skipped": False, "issue": issue_num}
            )
            continue

        # ── Update umbrella ────────────────────────────────────────────────
        owner_repo_str = skill_id  # fallback
        source_url = finding.get("sourceUrl", "")
        from scripts.lib.github_api import parse_owner_repo as _parse
        parsed = _parse(source_url) if source_url else None
        if parsed:
            owner_repo_str = f"{parsed[0]}/{parsed[1]}"

        umbrella_title = f"[upstream] {owner_repo_str} → {new_version}"
        existing_umbrella = _find_existing_issue(
            f"{owner_repo_str} → {new_version}", "upstream:release"
        )
        if existing_umbrella:
            print(
                f"  Umbrella for {owner_repo_str}@{new_version} already exists as #{existing_umbrella}; skipping.",
                file=sys.stderr,
            )
            summaries.append(
                {
                    "type": "update",
                    "skillId": skill_id,
                    "skipped": True,
                    "issue": existing_umbrella,
                }
            )
            continue

        component_adds = finding.get("componentAdds", [])
        component_removes = finding.get("componentRemoves", [])
        link_liveness = finding.get("linkLiveness", [])
        mode = finding.get("mode", "version-only")

        umbrella_body = render_umbrella_body(
            finding, mode, component_adds, component_removes, link_liveness
        )
        umbrella_num = _create_issue(
            umbrella_title,
            ["upstream:release", "needs-triage"],
            umbrella_body,
            dry_run=not apply,
            verbose=verbose,
        )

        # ── Child intakes for added components ────────────────────────────
        child_numbers: list[int] = []
        suite_gh = finding.get("sourceUrl", "")

        for slug in component_adds:
            child_title = f"[intake] {contributor}/{slug}"
            existing_child = _find_existing_issue(
                f"[intake] {contributor}/{slug}", "intake"
            )
            if existing_child:
                print(
                    f"  Child intake for {contributor}/{slug} already exists as #{existing_child}; skipping.",
                    file=sys.stderr,
                )
                child_numbers.append(existing_child)
                continue

            child_body = render_child_body(
                slug=slug,
                contributor=contributor,
                umbrella_number=umbrella_num or "?",
                suite_gh_url=suite_gh,
            )
            child_num = _create_issue(
                child_title,
                ["intake", "needs-triage", "upstream:child"],
                child_body,
                dry_run=not apply,
                verbose=verbose,
            )
            if child_num:
                child_numbers.append(child_num)

        # Edit umbrella to list child refs
        if umbrella_num:
            _edit_umbrella_body(umbrella_num, child_numbers, dry_run=not apply)

        summaries.append(
            {
                "type": "update",
                "skillId": skill_id,
                "umbrella": umbrella_num,
                "children": child_numbers,
                "skipped": False,
            }
        )

    return summaries
