import os
import re
import shutil
import subprocess
from pathlib import Path


def open_pr(username, tree_data, candidate_result=None):
    branch_name = f"update-tree-{username}"
    if candidate_result:
        title = f"[user] Update {username} skill tree - added {candidate_result}"
    else:
        title = f"[user] Update {username} skill tree"
    body = f"Detected new skills and confirmed fusions for {username}.\n\nAutomatically generated by Gaia plugin."
    print("Mock: Opening PR to gaia-registry/gaia")
    print(f"Branch: {branch_name}")
    print(f"Title: {title}")
    print(f"Body: {body}")
    print("Success: PR #42 opened.")
    return "https://github.com/gaia-registry/gaia/pull/42"


def _sanitize_branch_component(value):
    safe = re.sub(r"[^a-zA-Z0-9._-]+", "-", (value or "").strip()).strip("-").lower()
    return safe or "unknown"


def _build_similarity_index(similarity_rows):
    indexed = {}
    for row in similarity_rows or []:
        source = row.get("sourceSkillId")
        target = row.get("targetSkillId")
        score = row.get("score")
        if not source or not target:
            continue
        indexed.setdefault(source, []).append((score, target))
    for source in indexed:
        indexed[source].sort(key=lambda item: item[0], reverse=True)
    return indexed


def _github_file_url(source_repo, batch_id):
    """Build an expected GitHub URL for the batch file once committed."""
    if source_repo and "/" in source_repo:
        return f"https://github.com/{source_repo}/blob/main/registry-for-review/skill-batches/{batch_id}.json"
    return None


def build_intake_issue_body(batch_data):
    source_repo = batch_data.get("sourceRepo", "unknown")
    generated_at = batch_data.get("generatedAt", "unknown")
    batch_id = batch_data.get("batchId", "unknown")
    known_skills = batch_data.get("knownSkills", [])
    proposed_skills = batch_data.get("proposedSkills", [])
    similarity = _build_similarity_index(batch_data.get("similarity", []))
    file_url = _github_file_url(source_repo, batch_id)

    lines = [
        "## Gaia Draft Skill Intake",
        "",
        "Draft skill batch submitted for human review via `gaia push`.",
        "Reviewed skills must be promoted separately into `registry/gaia.json`.",
        "",
        "### Batch Summary",
        f"- **User:** `{batch_data.get('userId', 'unknown')}`",
        f"- **Source repo:** [`{source_repo}`](https://github.com/{source_repo})" if source_repo and "/" in source_repo else f"- **Source repo:** `{source_repo}`",
        f"- **Generated at:** `{generated_at}`",
        f"- **Batch ID:** `{batch_id}`",
        f"- **Known canonical skills:** `{len(known_skills)}`",
        f"- **Proposed new skills:** `{len(proposed_skills)}`",
    ]

    if file_url:
        lines.extend([
            "",
            f"**Batch file (after push):** [{batch_id}.json]({file_url})",
            f"> Commit and push `registry-for-review/skill-batches/{batch_id}.json` to make this link live.",
        ])

    lines.extend([
        "",
        "### Proposed Skills",
        "| ID | Name | Type | Similarity hints |",
        "|---|---|---|---|",
    ])

    if proposed_skills:
        for skill in proposed_skills:
            skill_id = skill.get("id", "")
            hints = similarity.get(skill_id, [])[:2]
            hint_text = ", ".join([f"`{target}` ({score:.3f})" for score, target in hints]) if hints else "-"
            lines.append(
                f"| `{skill_id}` | {skill.get('name', '')} | `{skill.get('type', '')}` | {hint_text} |"
            )
    else:
        lines.append("| - | - | - | - |")

    if known_skills:
        lines.extend(["", "### Detected Canonical Skills"])
        for s in known_skills:
            lines.append(f"- `{s.get('skillId', '')}`")

    lines.extend(
        [
            "",
            "### Reviewer Checklist",
            "- [ ] Reviewed each proposed skill for clarity and non-overlap.",
            "- [ ] Marked each candidate as: accept, rename, duplicate, needs evidence, or reject.",
            "- [ ] Verified similarity hints are directionally useful (not authoritative).",
            "- [ ] Noted any evidence gaps or requests for follow-up.",
            "",
            "### Maintainer Promotion Checklist",
            "- [ ] Convert accepted draft skills into canonical `registry/gaia.json` edits.",
            "- [ ] Run `gaia validate` and `gaia validate --intake` after promotion.",
            "- [ ] Close this issue once all proposed skills are resolved.",
            "",
            "_Automatically generated by `gaia push`._",
        ]
    )
    return "\n".join(lines)


# Keep old name as alias so existing imports don't break
def build_intake_pr_body(batch_data):
    return build_intake_issue_body(batch_data)


def _subprocess_env():
    env = os.environ.copy()
    package_parent = str(Path(__file__).resolve().parent.parent)
    pythonpath = [package_parent]
    existing = env.get("PYTHONPATH")
    if existing:
        pythonpath.extend(existing.split(os.pathsep))
    env["PYTHONPATH"] = os.pathsep.join(dict.fromkeys(path for path in pythonpath if path))
    return env


def _run(cmd, cwd):
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=_subprocess_env(),
        capture_output=True,
        text=True,
        check=False,
    )


def _gh_ready(cwd):
    if shutil.which("gh") is None:
        return False, "GitHub CLI (`gh`) is not installed."
    auth = _run(["gh", "auth", "status"], cwd=cwd)
    if auth.returncode != 0:
        return False, "GitHub CLI is not authenticated."
    return True, ""


def _print_manual_issue_steps(title, body_path):
    print("Issue creation skipped. Run this command manually:")
    print(
        f"  gh issue create --title \"{title}\" --body-file {body_path}"
        " --label draft-skills --label needs-review"
    )


def open_intake_issue(username, batch_data, batch_path=None, repo_root="."):
    """Create a GitHub issue for this skill intake batch."""
    title = f"[intake] {username} skill batch - {batch_data.get('sourceRepo', 'unknown')}"
    body = build_intake_issue_body(batch_data)
    body_path = os.path.join(repo_root, ".gaia-intake-issue-body.md")
    with open(body_path, "w", encoding="utf-8") as f:
        f.write(body)
        f.write("\n")

    ready, reason = _gh_ready(repo_root)
    if not ready:
        print(reason)
        _print_manual_issue_steps(title, body_path)
        return None

    issue = _run(
        [
            "gh",
            "issue",
            "create",
            "--title",
            title,
            "--body-file",
            body_path,
            "--label",
            "draft-skills",
            "--label",
            "needs-review",
        ],
        cwd=repo_root,
    )
    if issue.returncode != 0:
        print("Failed to create issue with gh.")
        print(issue.stderr.strip() or issue.stdout.strip())
        _print_manual_issue_steps(title, body_path)
        return None

    issue_url = issue.stdout.strip().splitlines()[-1] if issue.stdout.strip() else ""
    print(f"Success: intake issue opened ({issue_url}).")
    return issue_url or None


# Keep old name as alias so existing callers don't break
def open_intake_pr(username, batch_data, batch_path=None, repo_root="."):
    return open_intake_issue(username, batch_data, batch_path=batch_path, repo_root=repo_root)
