import os
import re
import shutil
import subprocess
from pathlib import Path


# open_pr — kept for impl.py compatibility (user skill-tree PR flow).
# The mock body below is the historic placeholder; the real GitHub PR creation
# path goes through open_intake_issue for intake batches.
def open_pr(username, tree_data, candidate_result=None):
    branchName = f"update-tree-{username}"
    if candidate_result:
        title = f"[user] Update {username} skill tree - added {candidate_result}"
    else:
        title = f"[user] Update {username} skill tree"
    body = f"Detected new skills and confirmed fusions for {username}.\n\nAutomatically generated by Gaia plugin."
    print("Mock: Opening PR to gaia-registry/gaia")
    print(f"Branch: {branchName}")
    print(f"Title: {title}")
    print(f"Body: {body}")
    print("Success: PR #42 opened.")
    return "https://github.com/gaia-registry/gaia/pull/42"


def _sanitize_branch_component(value):
    safe = re.sub(r"[^a-zA-Z0-9._-]+", "-", (value or "").strip()).strip("-").lower()
    return safe or "unknown"


def _build_similarity_index(similarity_rows):
    indexed = {}
    for row in similarity_rows or []:
        source = row.get("sourceSkillId")
        target = row.get("targetSkillId")
        score = row.get("score")
        if not source or not target:
            continue
        indexed.setdefault(source, []).append((score, target))
    for source in indexed:
        indexed[source].sort(key=lambda item: item[0], reverse=True)
    return indexed


def _github_file_url(source_repo, batch_id):
    """Build an expected GitHub URL for the batch file once committed."""
    if source_repo and "/" in source_repo:
        return f"https://github.com/{source_repo}/blob/main/registry-for-review/skill-batches/{batch_id}.json"
    return None


# ---------------------------------------------------------------------------
# _EVIDENCE_GRADE_EMOJI — visual grade badges used in issue body rendering.
# ---------------------------------------------------------------------------
_EVIDENCE_GRADE_EMOJI = {"A": "🥇", "B": "🥈", "C": "🥉"}


def _render_evidence_rows(evidence_list):
    """Return a markdown table string for a skill's evidence list, or a dash."""
    if not evidence_list:
        return "*none — needs Grade B+ before promotion*"
    rows = ["| Grade | Type | URL | Notes |", "|---|---|---|---|"] 
    for ev in evidence_list:
        grade = ev.get("grade", ev.get("class", "?"))
        emoji = _EVIDENCE_GRADE_EMOJI.get(str(grade).upper(), "")
        ev_type = ev.get("type", "-")
        url = ev.get("url", ev.get("source", "-"))
        notes = ev.get("notes", "").replace("|", "\\|")  # escape pipes inside table cells
        url_cell = f"[link]({url})" if url.startswith("http") else url
        rows.append(f"| {emoji} **{grade}** | `{ev_type}` | {url_cell} | {notes} |")
    return "\n".join(rows)


def _render_attribution_badge(attribution):
    """Return a one-line attribution summary string."""
    if not attribution:
        return "-"
    attr_type = attribution.get("type", "unknown")
    author = attribution.get("upstream_author", "")
    url = attribution.get("skill_file_url", "")
    badge = {
        "self-made": "✅ self-made",
        "aggregator": "⚠️ aggregator",
        "attributed": "👤 attributed",
        "abstract": "🔷 abstract",
    }.get(attr_type, f"❓ {attr_type}")
    parts = [badge]
    if author:
        parts.append(f"upstream: `{author}`")
    if url:
        short = url.split("/")[-1] or url
        parts.append(f"[{short}]({url})")
    return " · ".join(parts)


def _render_named_block(named, skillId):
    """Return a compact named-skill request summary, or empty string.

    skillId is passed directly to avoid deferred .format() which would crash
    if contributor or level contain brace characters.
    """
    if not named:
        return ""
    contributor = named.get("contributor", "?")
    level = named.get("level", "?")
    link = named.get("links_github", named.get("links", {}).get("github", ""))
    linkCell = f" · [blob link]({link})" if link else ""
    return f"📌 Named: `{contributor}/{skillId}`  ·  {level}{linkCell}"


def _render_skill_section(skill, similarityIndex):
    """Render one collapsible <details> block for a single proposed skill."""
    skillId = skill.get("id", "unknown")
    name = skill.get("name", skillId)
    skType = skill.get("type", "basic")
    description = skill.get("description", "-")
    prereqs = skill.get("prerequisites", [])
    attribution = skill.get("attribution", {})
    evidence = skill.get("evidence", [])
    named = skill.get("named", None)

    hints = similarityIndex.get(skillId, [])[:3]
    hintText = ", ".join([f"`{t}` ({s:.2f})" for s, t in hints]) if hints else "none"

    prereqText = ", ".join(f"`{p}`" for p in prereqs) if prereqs else "*none (basic)*"
    namedLine = _render_named_block(named, skillId) if named else ""

    block = [
        f"<details>",
        f"<summary><b><code>{skillId}</code></b> — {name} &nbsp;·&nbsp; <code>{skType}</code></summary>",
        "",
        f"**Description:** {description}",
        "",
        f"**Prerequisites:** {prereqText}",
        "",
        f"**Attribution:** {_render_attribution_badge(attribution)}",
        "",
        "**Evidence:**",
        "",
        _render_evidence_rows(evidence),
        "",
    ]
    if namedLine:
        block += [f"**Named skill request:** {namedLine}", ""]
    block += [
        f"**Similarity hints (top 3):** {hintText}",
        "",
        "**Reviewer decision:** *(replace with: `accept` · `rename <id>` · `duplicate <existing-id>` · `needs-evidence <what>` · `reject <reason>`)*",
        "",
        "</details>",
    ]
    return "\n".join(block)


def build_intake_issue_body(batch_data):
    """Build the GitHub issue body for a skill intake batch.

    Handles both the legacy scan-based batch format (flat proposed_skills list with
    minimal fields) and the richer --from-file format (full attribution, evidence,
    and named blocks per skill).  The richer format renders one collapsible
    <details> block per skill so reviewers can triage them independently within a
    single issue.
    """
    sourceRepo = batch_data.get("sourceRepo", "unknown")
    generatedAt = batch_data.get("generatedAt", "unknown")
    batchId = batch_data.get("batchId", "unknown")
    knownSkills = batch_data.get("knownSkills", [])
    proposedSkills = batch_data.get("proposedSkills", [])
    similarity = _build_similarity_index(batch_data.get("similarity", []))
    fileUrl = _github_file_url(sourceRepo, batchId)
    fromFile = batch_data.get("fromFile", False)

    repoLink = (
        f"[`{sourceRepo}`](https://github.com/{sourceRepo})"
        if sourceRepo and "/" in sourceRepo
        else f"`{sourceRepo}`"
    )
    via = "`gaia push --from-file`" if fromFile else "`gaia push`"
    lines = [
        "## Gaia Skill Batch Intake",
        "",
        f"Batch submitted via {via} · {len(proposedSkills)} skill(s) proposed.",
        "Reviewed skills must be promoted separately into `registry/gaia.json`.",
        "",
        "### Batch metadata",
        f"| Field | Value |",
        f"|---|---|",
        f"| User | `{batch_data.get('userId', 'unknown')}` |",
        f"| Source repo | {repoLink} |",
        f"| Generated at | `{generatedAt}` |",
        f"| Batch ID | `{batchId}` |",
        f"| Known canonical skills | `{len(knownSkills)}` |",
        f"| Proposed new skills | `{len(proposedSkills)}` |",
    ]

    if fileUrl:
        lines += [
            f"| Batch file | [{batchId}.json]({fileUrl}) |",
        ]

    lines += [
        "",
        "### Quick decision table",
        "*Fill in the Decision column — details for each skill are in the collapsible sections below.*",
        "",
        "| # | ID | Type | Attribution | Decision |",
        "|---|---|---|---|---|",
    ]
    for i, skill in enumerate(proposedSkills, 1):
        skillId = skill.get("id", "")
        skType = skill.get("type", "basic")
        attr = skill.get("attribution", {})
        attrType = attr.get("type", "-") if attr else "-"
        attrAuthor = attr.get("upstream_author", "") if attr else ""
        attrCell = f"`{attrType}`" + (f" (`{attrAuthor}`)") if attrAuthor else f"`{attrType}`"
        lines.append(
            f"| {i} | `{skillId}` | `{skType}` | {attrCell} | *(pending)* |"
        )

    if not proposedSkills:
        lines.append("| — | — | — | — | — |")

    if proposedSkills:
        lines += ["", "---", "", "### Skill details"]
        # fromFile batches always use rich <details> blocks.
        # Legacy scan batches fall back to flat table unless they carry rich fields.
        useRich = fromFile or any(
            skill.get("attribution") or skill.get("evidence") or skill.get("named")
            for skill in proposedSkills
        )
        if useRich:
            for skill in proposedSkills:
                lines += ["", _render_skill_section(skill, similarity)]
        else:
            lines += [
                "",
                "| ID | Name | Type | Similarity hints |",
                "|---|---|---|---|",
            ]
            for skill in proposedSkills:
                skillId = skill.get("id", "")
                hints = similarity.get(skillId, [])[:2]
                hintText = (
                    ", ".join([f"`{t}` ({s:.3f})" for s, t in hints]) if hints else "-"
                )
                lines.append(
                    f"| `{skillId}` | {skill.get('name', '')} | `{skill.get('type', '')}` | {hintText} |"
                )

    if knownSkills:
        lines += ["", "### Detected canonical skills (already in registry)"]
        for s in knownSkills:
            lines.append(f"- `{s.get('skillId', '')}`")

    # ── reviewer + maintainer checklists ─────────────────────────────────────
    lines += [
        "",
        "---",
        "",
        "### Reviewer checklist",
        "- [ ] Every proposed skill has a decision in the Quick decision table above.",
        "- [ ] Attribution flags (`aggregator` / `attributed`) have been verified — named entry uses the upstream author, not the proposer.",
        "- [ ] Similarity hints checked; no undetected duplicates.",
        "- [ ] Evidence Grade B+ confirmed for every `accept` decision.",
        "",
        "### Maintainer promotion checklist",
        "- [ ] Accepted skills promoted via `gaia dev add` on a `review/meta/` branch.",
        "- [ ] `gaia validate` + `gaia validate --intake` pass.",
        "- [ ] `gaia dev docs` run and Class S artifacts committed.",
        "- [ ] Named skill PRs opened for any skill with an accepted `named:` block.",
        "- [ ] This issue closed with a link to the promotion PR.",
        "",
        "> **Yggdrasil II staging:** PRs introducing `type: fusion` nodes must target",
        "> `dev/yggdrasil-ii-staging` until schema sub-issue #995 merges to `main`.",
        "",
        "_Automatically generated by `gaia push`._",
    ]
    return "\n".join(lines)


# Keep old name as alias so existing imports don't break
def build_intake_pr_body(batch_data):
    return build_intake_issue_body(batch_data)


def _subprocess_env():
    env = os.environ.copy()
    package_parent = str(Path(__file__).resolve().parent.parent)
    pythonpath = [package_parent]
    existing = env.get("PYTHONPATH")
    if existing:
        pythonpath.extend(existing.split(os.pathsep))
    env["PYTHONPATH"] = os.pathsep.join(dict.fromkeys(path for path in pythonpath if path))
    return env


def _run(cmd, cwd):
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=_subprocess_env(),
        capture_output=True,
        text=True,
        check=False,
    )


def _gh_ready(cwd):
    if shutil.which("gh") is None:
        return False, "GitHub CLI (`gh`) is not installed."
    auth = _run(["gh", "auth", "status"], cwd=cwd)
    if auth.returncode != 0:
        return False, "GitHub CLI is not authenticated."
    return True, ""


def _print_manual_issue_steps(title, body_path):
    print("Issue creation skipped. Run this command manually:")
    print(
        f"  gh issue create --title \"{title}\" --body-file {body_path}"
        " --label draft-skills --label needs-review"
    )


def _build_intake_issue_title(batch_data):
    """Generate a human-readable issue title from batch contents."""
    proposed = batch_data.get("proposedSkills", [])
    count = len(proposed)
    if count == 1:
        return f"[intake] single: {proposed[0].get('id', 'unknown')}"
    if count <= 4:
        ids = ", ".join(s.get("id", "?") for s in proposed[:4])
        return f"[intake] {count} skills: {ids}"
    sources = {}
    for s in proposed:
        attr = s.get("attribution") or {}
        author = attr.get("upstream_author", "") or batch_data.get("userId", "")
        sources[author] = sources.get(author, 0) + 1
    top = sorted(sources.items(), key=lambda x: -x[1])
    topLabel = top[0][0] if top else batch_data.get("sourceRepo", "unknown").split("/")[-1]
    return f"[intake] {count} skills from {topLabel}"


def open_intake_issue(username, batch_data, batch_path=None, repo_root="."):
    """Create a GitHub issue for this skill intake batch."""
    title = _build_intake_issue_title(batch_data)
    body = build_intake_issue_body(batch_data)
    bodyPath = os.path.join(repo_root, ".gaia-intake-issue-body.md")
    with open(bodyPath, "w", encoding="utf-8") as f:
        f.write(body)
        f.write("\n")

    ready, reason = _gh_ready(repo_root)
    if not ready:
        print(reason)
        _print_manual_issue_steps(title, bodyPath)
        return None

    issue = _run(
        ["gh", "issue", "create", "--title", title,
         "--body-file", bodyPath,
         "--label", "draft-skills", "--label", "needs-review"],
        cwd=repo_root,
    )
    if issue.returncode != 0:
        print("Failed to create issue with gh.")
        print(issue.stderr.strip() or issue.stdout.strip())
        _print_manual_issue_steps(title, bodyPath)
        return None

    issueUrl = issue.stdout.strip().splitlines()[-1] if issue.stdout.strip() else ""
    print(f"Success: intake issue opened ({issueUrl}).")
    try:
        os.remove(bodyPath)
    except OSError:
        pass
    return issueUrl or None


# Keep old name as alias so existing callers don't break
def open_intake_pr(username, batch_data, batch_path=None, repo_root="."):
    return open_intake_issue(username, batch_data, batch_path=batch_path, repo_root=repo_root)
