/**
 * Gaia site Worker — static assets + repo-bound badge validation.
 *
 * Deploy model: Cloudflare **Worker with Static Assets** (`wrangler deploy`,
 * `[assets] directory = "docs"`).
 *
 * ## Why this design (no run_worker_first)
 *
 * Cloudflare serves a matching static asset *before* invoking the Worker, and
 * `run_worker_first` (which would flip that) proved unreliable across this
 * project's deploy pipeline. So instead of fighting precedence, we remove the
 * conflict: the real badge SVGs are generated to /badges/_assets/<handle>/
 * (a 3-segment path), leaving the public /badges/<handle>/<file>.svg
 * (2-segment) path with NO static asset. The Worker therefore runs as the
 * normal no-asset fallback for every badge request — the one behaviour that
 * works reliably in production — validates `?repo=`, and serves the real SVG
 * from the _assets source (or the validating badge on a mismatch).
 *
 * Routes:
 *   /badges/<handle>/<file>.svg              → validated (this worker)
 *   /badges/_assets/<handle>/<file>.svg      → the real SVGs (static, internal source)
 *   /badges/{powered-by-gaia,not-found}.svg  → static (1-segment, never validated)
 *   /badges/samples/*                        → static (has assets, worker not invoked)
 *   /badges/registry.json, /badges/, ...     → static
 *
 * Behaviour for /badges/<handle>/<file>.svg:
 *   - No `?repo=`            → serve the real SVG (back-compat for un-migrated READMEs).
 *   - `?repo=` matches one   → serve the real SVG.
 *     of contributors[handle].repos in /badges/registry.json
 *   - `?repo=` doesn't match → serve /badges/not-found.svg (the "validating…"
 *     badge) at THIS url, HTTP 200, so GitHub's camo proxy caches a stable image.
 *
 * ## Caching (handled here, not via a CDN cache rule)
 *
 * Responses are generated by the Worker (not served as static assets), so
 * Cloudflare does not edge-cache them — the Worker runs per request and each
 * `?repo=` is evaluated fresh (no cross-repo collision). We still send a 24h
 * `max-age` so GitHub camo (which keys on the full URL incl. query) caches each
 * (handle, file, repo) image for ~24h.
 */

const ONE_DAY = 60 * 60 * 24;
const CACHE_HEADERS = `public, max-age=${ONE_DAY}`;

// Real SVGs live here (3-segment path → never matches BADGE_RE, served static).
const ASSET_BASE = "/badges/_assets";

// Public validated route: /badges/<handle>/<file>.svg (exactly two segments).
const BADGE_RE = /^\/badges\/([^/]+)\/([^/]+\.svg)$/;

// Defensive guards — these normally resolve to static assets (so the worker is
// never invoked for them), but if one ever reaches the worker, pass it through.
const PASSTHROUGH_FILES = new Set(["powered-by-gaia.svg", "not-found.svg"]);
const PASSTHROUGH_HANDLES = new Set(["samples", "_assets"]);

/**
 * Structured log line — one JSON object per badge decision (Cloudflare Workers
 * Logs picks these up; tail with `wrangler tail`). Schema kept stable:
 *   evt "badge_request" | handle | file | repo_claimed (null if absent)
 *   | state "valid" | "validating" | "passthrough_no_repo" | "passthrough_static"
 */
function logEvent(handle, file, repo, state) {
  console.log(JSON.stringify({
    evt: "badge_request", handle, file, repo_claimed: repo || null, state,
  }));
}

export default {
  async fetch(request, env) {
    if (request.method !== "GET") return env.ASSETS.fetch(request);

    const url = new URL(request.url);
    const match = url.pathname.match(BADGE_RE);
    if (!match) return env.ASSETS.fetch(request);

    const handle = match[1];
    const file = match[2];

    if (PASSTHROUGH_HANDLES.has(handle) || PASSTHROUGH_FILES.has(file)) {
      logEvent(handle, file, null, "passthrough_static");
      return env.ASSETS.fetch(request);
    }

    const repo = url.searchParams.get("repo");

    // Back-compat: badges in existing READMEs may not include `?repo=` yet.
    if (!repo) {
      logEvent(handle, file, null, "passthrough_no_repo");
      return serveReal(handle, file, url, request, env);
    }

    const approved = await getApprovedRepos(handle, env, url);
    if (approved && approved.includes(repo)) {
      logEvent(handle, file, repo, "valid");
      return serveReal(handle, file, url, request, env);
    }

    // Repo doesn't match (or unknown handle) — serve the validating badge.
    logEvent(handle, file, repo, "validating");
    const notFoundUrl = new URL("/badges/not-found.svg", url.origin);
    const nf = await env.ASSETS.fetch(new Request(notFoundUrl, request));
    if (!nf.ok) {
      // not-found.svg missing — better to render the real badge than a broken image.
      return serveReal(handle, file, url, request, env);
    }
    const body = await nf.arrayBuffer();
    return new Response(body, {
      status: 200,
      headers: {
        "content-type": "image/svg+xml; charset=utf-8",
        "cache-control": CACHE_HEADERS,
        "x-gaia-badge-state": "validating",
        "x-gaia-badge-handle": handle,
        "x-gaia-badge-repo-claimed": repo,
      },
    });
  },
};

/**
 * Serve the real badge SVG from its internal _assets source, re-headered with a
 * 24h cache and an `x-gaia-badge-state: valid` marker. A 404 here means the
 * badge genuinely doesn't exist for that handle/file.
 */
async function serveReal(handle, file, url, request, env) {
  const realUrl = new URL(`${ASSET_BASE}/${handle}/${file}`, url.origin);
  const resp = await env.ASSETS.fetch(new Request(realUrl, request));
  if (!resp.ok) return resp;
  const body = await resp.arrayBuffer();
  const headers = new Headers(resp.headers);
  headers.set("content-type", "image/svg+xml; charset=utf-8");
  headers.set("cache-control", CACHE_HEADERS);
  headers.set("x-gaia-badge-state", "valid");
  return new Response(body, { status: 200, headers });
}

// ── registry.json caching ────────────────────────────────────────────────────
// Cache the parsed contributor list in module scope (reused across requests on
// the same edge node). 24h TTL; a redeploy resets it.
let _cache = { at: 0, data: null };

async function getApprovedRepos(handle, env, url) {
  const now = Date.now();
  if (_cache.data && now - _cache.at < ONE_DAY * 1000) {
    return (_cache.data[handle] && _cache.data[handle].repos) || [];
  }
  try {
    const registryUrl = new URL("/badges/registry.json", url.origin);
    const r = await env.ASSETS.fetch(new Request(registryUrl, { cf: { cacheTtl: ONE_DAY } }));
    if (!r.ok) return [];
    const json = await r.json();
    _cache = { at: now, data: json.contributors || {} };
    return (_cache.data[handle] && _cache.data[handle].repos) || [];
  } catch {
    return [];
  }
}
